#ifndef UILABTESTRUNNER_GLOBAL_H
#define UILABTESTRUNNER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UILABTESTRUNNER_LIBRARY)
#  define UILABTESTRUNNERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UILABTESTRUNNERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UILABTESTRUNNER_GLOBAL_H
