#ifndef LIBUILABUTILSGUI_GLOBAL_H
#define LIBUILABUTILSGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBUILABUTILSGUI_LIBRARY)
#  define LIBUILABUTILSGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBUILABUTILSGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBUILABUTILSGUI_GLOBAL_H
